### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by LeopoldoGurgel** [LeopoldoGurgel/prework-study-guide#2]
# CSS

## User Story
As a bootcamp student 
I want the prework notes to be structured on a webpage
So that I can easily find and read the information

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I view the study guide
THEN I see a dark blue header and footer, and four boxes with a shadow

**Comment by Grs257** [comment]
Hello there you can  clear your problem by maintaining different div for header and footer with different ID's ,then you can modify as you like with the ID's
for better understanding you can check out the YOUTUBE channel name "CodewithHarry CSS playlist"
